Testing class methods with rspec
emasdev/tic-tac-toe-1 pull request #1
Opened 2020-07-08 17:15 UTC by emasdev

- board tested
- scores tested
- player tested

2020-07-09 00:40 UTC, adaorachi requested changes
### Hi @emasdev and @yahir91, :wave: 

Well done on the completion of the first draft of this project. Your test suite works fine, however there are a couple of mandatory changes to be implemented to get it approved.

---
### CHANGES REQUIRED :recycle: 

---

- [x] The README content should be descriptive. Currently, you barely have any content in the README file. Kindly update your README with the necessary contents and also ensure you include a Testing Game Logic section to it describing how to run the test in a local machine, the tool used for the TDD and the possible results which are gotten from the test.

- [x] Your Pull Request does not have a descriptive summary. It should briefly explain the features implemented in this project. Kindly update it to be more explanatory.

- [x] Kindly ensure that all the public methods of the classes in the OOP project are tested.

2020-07-09 00:52 UTC, adaorachi requested changes

2020-07-09 00:52 UTC, adaorachi commented on spec/player_spec.rb
> +  end
- [ ] Currently, you have all methods for each class wrapped in one `describe` block and which should not be. You should ensure that the specs for each method be wrapped in one `describe` block. 
For example in the highlighted code above, it should be wrapped in its own `describe` block, with one `it` block for each expected behavior just like you have it and the behaviors should test for positive and/or negative cases.

#### **Kindly note that this does NOT ONLY apply to the highlighted code, ensure you make these changes in all three test files as it appears that the structure for defining a `describe` block was not exactly followed.**

2020-07-09 00:53 UTC, adaorachi commented
---

### Kindly implement the changes stated above and request for another code review when you are done.

---

Should you have any question, please do reach out to me on Slack with the username - **@adaorachi**

Happy Coding :relaxed: 

**MaryAnn Chukwuka**

2020-07-09 22:37 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x]  Lets test methods in `logic.rb` 
- [x] I can see board class in `logic.rb` ,you have one already in `board.rb`
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-07-10 03:42 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job team :+1:
- You can now merge these changes. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-07-10 06:01 UTC, merged